# ---------------------------------------------------------------------------------------------------
# Slack channel configuration
# ---------------------------------------------------------------------------------------------------

webhook_url: "[YOUR_WEBHOOK_URL]"
username: "USERNAME"
channel: "CHANNEL"
timeout: 5s
